import styled from 'styled-components';
import { theme } from '../styles/theme';

const Section=styled.section`padding:35px 0 24px;`;
const Card=styled.div`position:relative;overflow:hidden;background:${theme.colors.ink};color:white;border-radius:${theme.radius.large};padding:clamp(35px,6vw,75px);&::after{content:'↗';position:absolute;right:-20px;top:-65px;font-size:15rem;line-height:1;color:${theme.colors.blue};opacity:.45;transform:rotate(-8deg)}small{font:800 .78rem ${theme.fonts.mono};text-transform:uppercase;letter-spacing:.1em;color:${theme.colors.lime}}h2{position:relative;z-index:1;font-size:clamp(3rem,7vw,6.7rem);line-height:.9;letter-spacing:-.07em;max-width:900px;margin:22px 0 26px}p{position:relative;z-index:1;color:#bbb;max-width:570px;font-size:1.05rem}`;
const ContactGrid=styled.div`position:relative;z-index:1;display:grid;grid-template-columns:.65fr 1.35fr;gap:55px;align-items:start;margin-top:50px;@media(max-width:820px){grid-template-columns:1fr;gap:30px;}`;
const Aside=styled.div`h3{font-size:1.3rem;margin:0 0 12px}p{font-size:.92rem;margin-bottom:25px}`;
const Links=styled.div`display:flex;flex-wrap:wrap;gap:9px;a{padding:10px 13px;border:1px solid #666;border-radius:10px;font-weight:800;background:#242424;transition:.2s;&:hover{transform:translateY(-3px);border-color:white}}`;
const Form=styled.form`display:grid;grid-template-columns:1fr 1fr;gap:15px;padding:25px;background:${theme.colors.white};color:${theme.colors.ink};border:1.5px solid #777;border-radius:20px;box-shadow:7px 8px 0 ${theme.colors.blue};@media(max-width:560px){grid-template-columns:1fr;padding:18px}`;
const Field=styled.label<{ $wide?:boolean }>`display:grid;gap:7px;${p=>p.$wide&&'grid-column:1 / -1;'}span{font:800 .7rem ${theme.fonts.mono};text-transform:uppercase;letter-spacing:.06em}input,textarea{width:100%;border:1.5px solid ${theme.colors.line};border-radius:10px;padding:12px 13px;background:${theme.colors.paper};color:${theme.colors.ink};outline:0;&:focus{border-color:${theme.colors.blue};box-shadow:0 0 0 3px rgba(49,87,226,.15)}}textarea{min-height:135px;resize:vertical}`;
const Submit=styled.button`grid-column:1 / -1;justify-self:start;border:1.5px solid ${theme.colors.line};border-radius:11px;background:${theme.colors.lime};padding:12px 18px;font-weight:900;box-shadow:3px 4px 0 ${theme.colors.line};cursor:pointer;transition:.18s transform,.18s box-shadow;&:hover{transform:translate(2px,2px);box-shadow:1px 2px 0 ${theme.colors.line}}`;
const Footer=styled.footer`display:flex;justify-content:space-between;gap:20px;padding:25px 4px 0;color:${theme.colors.muted};font:700 .7rem ${theme.fonts.mono};text-transform:uppercase;@media(max-width:600px){flex-direction:column}`;

const Contact=()=> <Section id="contact"><div className="container"><Card><small>Next mission?</small><h2>Have a weird idea worth building?</h2><p>Tell me what you’re working on, what you need help with, or simply say hello. I’ll get back to you by email.</p><ContactGrid><Aside><h3>Elsewhere on the internet</h3><p>Prefer a direct message? Find me through any of these channels.</p><Links><a href="mailto:nagashrana@gmail.com">Email ↗</a><a href="https://github.com/rananagash" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/rana-nagash" target="_blank" rel="noreferrer">LinkedIn ↗</a></Links></Aside><Form action="https://formsubmit.co/nagashrana@gmail.com" method="POST"><input type="hidden" name="_subject" value="New message from Rana's portfolio"/><input type="hidden" name="_captcha" value="false"/><input type="text" name="_honey" style={{display:'none'}} tabIndex={-1} autoComplete="off"/><Field><span>Name</span><input name="name" type="text" autoComplete="name" placeholder="Your name" required/></Field><Field><span>Email</span><input name="email" type="email" autoComplete="email" placeholder="you@example.com" required/></Field><Field $wide><span>Subject</span><input name="subject" type="text" placeholder="What are we building?" required/></Field><Field $wide><span>Message</span><textarea name="message" placeholder="A few details about your idea..." required/></Field><Submit type="submit">Send message ↗</Submit></Form></ContactGrid></Card><Footer><span>Designed + built by Rana Nagash</span><span>Toronto · 2026</span></Footer></div></Section>;
export default Contact;
