import { useState } from 'react';
import styled, { keyframes } from 'styled-components';
import { theme } from '../styles/theme';

const pulse=keyframes`0%,100%{box-shadow:0 0 0 0 rgba(201,240,92,.5)}50%{box-shadow:0 0 0 10px rgba(201,240,92,0)}`;
const Section=styled.section`padding:120px 0;background:${theme.colors.blue};color:white;overflow:hidden;`;
const Head=styled.div`max-width:760px;margin-bottom:45px;small{font:800 .78rem ${theme.fonts.mono};text-transform:uppercase;letter-spacing:.1em;color:${theme.colors.lime}}h2{font-size:clamp(2.8rem,6vw,5.7rem);letter-spacing:-.065em;line-height:.95;margin:14px 0 20px}p{font-size:1.08rem;color:#dbe3ff;max-width:620px}`;
const Window=styled.div`border:2px solid ${theme.colors.ink};border-radius:24px;background:${theme.colors.paper};color:${theme.colors.ink};box-shadow:12px 14px 0 ${theme.colors.ink};overflow:hidden;`;
const Bar=styled.div`height:48px;border-bottom:2px solid ${theme.colors.ink};display:flex;align-items:center;gap:7px;padding:0 17px;background:${theme.colors.white};i{width:11px;height:11px;border:1px solid ${theme.colors.ink};border-radius:50%;background:${theme.colors.orange}i:nth-child(2){background:${theme.colors.lime}}i:nth-child(3){background:#9db1ff}}span{margin-left:auto;font:700 .7rem ${theme.fonts.mono}}`;
const Workspace=styled.div`display:grid;grid-template-columns:1.2fr .8fr;min-height:440px;@media(max-width:760px){grid-template-columns:1fr;}`;
const Graph=styled.div`position:relative;display:grid;place-items:center;padding:45px;min-height:360px;background-image:linear-gradient(rgba(24,24,23,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(24,24,23,.07) 1px,transparent 1px);background-size:26px 26px;&::before,&::after{content:'';position:absolute;height:2px;width:32%;background:${theme.colors.ink};left:34%;top:50%;transform:rotate(25deg)}&::after{transform:rotate(-25deg)}`;
const Node=styled.div<{ $position:string;$active?:boolean }>`position:absolute;${p=>p.$position};z-index:2;width:116px;min-height:76px;padding:13px;background:${p=>p.$active?theme.colors.lime:theme.colors.white};border:2px solid ${theme.colors.ink};border-radius:15px;box-shadow:4px 5px 0 ${theme.colors.ink};font:800 .72rem/1.4 ${theme.fonts.mono};transition:.3s transform,.3s background;${p=>p.$active&&`animation:${pulse} 1.4s infinite;transform:translateY(-5px);`}span{display:block;margin-top:7px;color:${theme.colors.muted};font-size:.62rem}@media(max-width:500px){width:96px;}`;
const Panel=styled.div`border-left:2px solid ${theme.colors.ink};padding:30px;display:flex;flex-direction:column;@media(max-width:760px){border-left:0;border-top:2px solid ${theme.colors.ink};}`;
const Log=styled.div`flex:1;font:700 .75rem/1.7 ${theme.fonts.mono};p{padding-bottom:10px;border-bottom:1px dashed #bbb;margin-bottom:10px}b{color:${theme.colors.blue}}`;
const Prompt=styled.div`display:flex;gap:8px;margin-top:20px;input{min-width:0;flex:1;border:2px solid ${theme.colors.ink};border-radius:10px;padding:11px;background:white}button{border:2px solid ${theme.colors.ink};border-radius:10px;background:${theme.colors.orange};font-weight:900;padding:10px 14px;cursor:pointer;box-shadow:3px 3px 0 ${theme.colors.ink};&:active{transform:translate(2px,2px);box-shadow:1px 1px 0}}`;

const Playground=()=>{const [run,setRun]=useState(0);const [prompt,setPrompt]=useState('Find a story in TTC delay data');const messages=[['Ready','Waiting for a tiny mission.'],['Researching','Patterns found across 12,480 records.'],['Building','Visualization and narrative assembled.'],['Complete','A curious story is ready to explore.']];const m=messages[run];const advance=()=>{setRun(1);window.setTimeout(()=>setRun(2),650);window.setTimeout(()=>setRun(3),1300)};return <Section id="playground"><div className="container"><Head><small>Interactive experiment / no API required</small><h2>Meet the tiny agent team.</h2><p>A playful simulation of how I break ambiguous ideas into research, building, and review. Give the team a mission and watch the handoff.</p></Head><Window><Bar><i/><i/><i/><span>agent_playground.exe</span></Bar><Workspace><Graph><Node $position="left:8%;top:39%" $active={run===1}>⌕ RESEARCH<span>gather context</span></Node><Node $position="right:8%;top:16%" $active={run===2}>⚙ BUILDER<span>make the thing</span></Node><Node $position="right:8%;bottom:12%" $active={run===3}>✦ REVIEWER<span>polish + ship</span></Node></Graph><Panel><Log aria-live="polite"><p><b>mission:</b> {prompt}</p><p><b>status:</b> {m[0]}</p><p>→ {m[1]}</p>{run===3&&<p><b>output:</b> Three delay hotspots, one surprising rush-hour pattern, and a story worth telling.</p>}</Log><Prompt><label className="sr-only" htmlFor="mission">Agent mission</label><input id="mission" value={prompt} onChange={e=>{setPrompt(e.target.value);setRun(0)}}/><button type="button" onClick={advance}>Run ↗</button></Prompt></Panel></Workspace></Window></div></Section>};
export default Playground;
